version: "3.1"

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: monpassword
      MYSQL_DATABASE: windr
      MYSQL_USER: myuser
      MYSQL_PASSWORD: monpassword
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: monpassword
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
      